// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB28iIsSorBucThmsGxnmabM_23o9FjS-s',
    appId: '1:425721399185:web:beeff514b67fe42172bc30',
    messagingSenderId: '425721399185',
    projectId: 'ogustavoress-golden-vault-app',
    authDomain: 'ogustavoress-golden-vault-app.firebaseapp.com',
    storageBucket: 'ogustavoress-golden-vault-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1pX0o5k-AsukqIQQBGtYWJE46ujoUn-4',
    appId: '1:425721399185:android:44f3e1f47ad2bec372bc30',
    messagingSenderId: '425721399185',
    projectId: 'ogustavoress-golden-vault-app',
    storageBucket: 'ogustavoress-golden-vault-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJUh7sjLUZtvGV6239lFKuNckX73ikdbQ',
    appId: '1:425721399185:ios:45068f8ef435523f72bc30',
    messagingSenderId: '425721399185',
    projectId: 'ogustavoress-golden-vault-app',
    storageBucket: 'ogustavoress-golden-vault-app.firebasestorage.app',
    iosBundleId: 'br.com.ogustavoress.checkpoint3550983552041',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJUh7sjLUZtvGV6239lFKuNckX73ikdbQ',
    appId: '1:425721399185:ios:45068f8ef435523f72bc30',
    messagingSenderId: '425721399185',
    projectId: 'ogustavoress-golden-vault-app',
    storageBucket: 'ogustavoress-golden-vault-app.firebasestorage.app',
    iosBundleId: 'br.com.ogustavoress.checkpoint3550983552041',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB28iIsSorBucThmsGxnmabM_23o9FjS-s',
    appId: '1:425721399185:web:aab7e8a66864b04672bc30',
    messagingSenderId: '425721399185',
    projectId: 'ogustavoress-golden-vault-app',
    authDomain: 'ogustavoress-golden-vault-app.firebaseapp.com',
    storageBucket: 'ogustavoress-golden-vault-app.firebasestorage.app',
  );

}